[nixpacks]
name = "vstory-backend"
version = 1

[phases.setup]
nixpkgs_archive = "nixpkgs#234"

[phases.install]
cmds = [
    "npm ci",
    "npx prisma generate"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/index.js"
