[phases.setup]
nixPkgs = ["nodejs_20", "openssl-3.0.13", "pkg-config"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "node dist/index.js"
